#!/bin/sh
bspc rule -r "*"

wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

xrdb -merge $HOME/.Xdefaults &
xrdb -merge $HOME/.Xresources &
xrdb ~/.Xresources &

killall bspswallow
pidof bspswallow | bspswallow &

feh --bg-fill ~/.config/wall.jpg &

###---WORKSPACES---###
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6'
		let name++
	done
}

workspaces


#### BSPWM configuration ####

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-left_DP-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-right_HDMI-0)

## -------- Rules ----------------------##
# remove all rules first


bspc rule -a TopTracker state=floating focus=on desktop="^4"

#  Work
declare -a work=(Upwork com.freelancer.workspace.launcher.Bootstrap)
for i in ${work[@]}; do
   bspc rule -a $i desktop='^4' state=floating follow=on focus=on; done


#  Communication
declare -a communication=(qBittorrent Transmission-gtk)
for i in ${communication[@]}; do
   bspc rule -a $i desktop='^7' state=floating follow=on focus=on; done


#  Communication
declare -a communication=(Mailspring Thunderbird)
for i in ${communication[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done


#  Messaging
declare -a media=(Skype Slack Telegram)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^9' state=floating follow=on focus=on; done

# startup application
startupapps &
