#!/bin/sh

function launch() {
  local running
  running="$(pidof "$1")"
  [ "$running" ] && kill -9 $(pidof $1)
  eval "$* &"
}


function AutoStartApps() {
	# Kill any running instances of bspc to prevent multiple
	# instances of "workspaces" script in eww rices to run at once
	killall bspc

	launch sxhkd &
  launch picom -b --experimental-backends &
	xsetroot -cursor_name left_ptr &
  xset r rate 300 50 &
  unclutter &
  bspswallow &

}


AutoStartApps()
